# Generated by Django 5.0.2 on 2024-02-22 09:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapagnt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="countryboundery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="DEFAULT VALUE", max_length=140)),
                ("type", models.CharField(default="DEFAULT VALUE", max_length=140)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="districtsboundery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dist_name", models.CharField(max_length=30)),
                ("state_name", models.CharField(max_length=50)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="mapmakermodel",
            options={"verbose_name_plural": "mapmakermodel"},
        ),
    ]
