# Generated by Django 5.0.2 on 2024-03-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapagnt", "0002_countryboundery_districtsboundery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countryboundery",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="countryboundery",
            name="type",
            field=models.CharField(max_length=20),
        ),
    ]
