# Generated by Django 5.0.2 on 2024-03-30 19:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapagnt", "0003_alter_countryboundery_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pipeline", "Pipe Line"),
                            ("roadrehabilitation", "Road Rehabilitation"),
                            ("drainagerehabilitation", "Drainage Rehabilitation"),
                            ("municipalfacility", "Municipal Facility"),
                            ("governmentfacility", "Government Facility"),
                        ],
                        max_length=50,
                    ),
                ),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("design", "Design"),
                            ("inProgress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=200, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
