# Generated by Django 5.0.2 on 2024-04-04 09:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapagnt", "0005_projectsmapmodel_delete_mapmakermodel_delete_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectsmapmodel",
            old_name="address",
            new_name="projectaddress",
        ),
        migrations.RenameField(
            model_name="projectsmapmodel",
            old_name="budget",
            new_name="projectbudget",
        ),
        migrations.RenameField(
            model_name="projectsmapmodel",
            old_name="latitude",
            new_name="projectlatitude",
        ),
        migrations.RenameField(
            model_name="projectsmapmodel",
            old_name="location",
            new_name="projectlocation",
        ),
        migrations.RenameField(
            model_name="projectsmapmodel",
            old_name="longitude",
            new_name="projectlongitude",
        ),
        migrations.RenameField(
            model_name="projectsmapmodel",
            old_name="name",
            new_name="projectname",
        ),
        migrations.RenameField(
            model_name="projectsmapmodel",
            old_name="status",
            new_name="projectstatus",
        ),
        migrations.RenameField(
            model_name="projectsmapmodel",
            old_name="type",
            new_name="projecttype",
        ),
        migrations.CreateModel(
            name="PipelineProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipestartlat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pipestartlon", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "pipelinestart_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("pipelineendlat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pipelineendlon", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "pipelineend_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "projectaddress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_projects_address",
                        to="mapagnt.projectsmapmodel",
                    ),
                ),
                (
                    "projectbudget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_projects_budget",
                        to="mapagnt.projectsmapmodel",
                    ),
                ),
                (
                    "projectname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_projects_name",
                        to="mapagnt.projectsmapmodel",
                    ),
                ),
                (
                    "projectstatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_projects_status",
                        to="mapagnt.projectsmapmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadRehabilitationProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roadstartlat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("roadstartlon", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "RoadRehabstart_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("roadendlat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("roadendlon", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "RoadRehabend_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "projectaddress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_rehabilitation_projects_address",
                        to="mapagnt.projectsmapmodel",
                    ),
                ),
                (
                    "projectbudget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_rehabilitation_projects_budget",
                        to="mapagnt.projectsmapmodel",
                    ),
                ),
                (
                    "projectname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_rehabilitation_projects_name",
                        to="mapagnt.projectsmapmodel",
                    ),
                ),
                (
                    "projectstatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="road_rehabilitation_projects_status",
                        to="mapagnt.projectsmapmodel",
                    ),
                ),
            ],
        ),
    ]
