# Generated by Django 5.0.2 on 2024-04-04 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapagnt", "0006_rename_address_projectsmapmodel_projectaddress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipelineproject",
            name="projectaddress",
        ),
        migrations.RemoveField(
            model_name="pipelineproject",
            name="projectbudget",
        ),
        migrations.RemoveField(
            model_name="pipelineproject",
            name="projectstatus",
        ),
        migrations.RemoveField(
            model_name="roadrehabilitationproject",
            name="projectaddress",
        ),
        migrations.RemoveField(
            model_name="roadrehabilitationproject",
            name="projectbudget",
        ),
        migrations.RemoveField(
            model_name="roadrehabilitationproject",
            name="projectstatus",
        ),
    ]
