# Generated by Django 5.0.2 on 2024-04-09 11:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapagnt", "0007_remove_pipelineproject_projectaddress_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="projectcoordinatorinformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coordinatorname", models.CharField(max_length=100)),
                ("coordinatordesignation", models.CharField(max_length=100)),
                ("coordinatoremail", models.EmailField(max_length=254)),
                ("coordinatorphone_number", models.CharField(max_length=15)),
                ("coordinatoraddress", models.CharField(max_length=200)),
                ("coordinatorcity", models.CharField(max_length=100)),
                ("coordinatorstate", models.CharField(max_length=100)),
                ("coordinatorcountry", models.CharField(max_length=100)),
                ("coordinatorzip_code", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="roadrehabilitationproject",
            name="projectname",
        ),
        migrations.CreateModel(
            name="onepproject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onepname", models.CharField(max_length=100)),
                (
                    "oneptype",
                    models.CharField(
                        choices=[
                            ("municipalfacility", "Municipal Facility"),
                            ("governmentfacility", "Government Facility"),
                            ("communityfacilities", "Community Facilities"),
                            ("policestation", "Police Station"),
                            ("parkandgardens", "Park and Gardens"),
                        ],
                        max_length=50,
                    ),
                ),
                ("onepbudget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "onepstatus",
                    models.CharField(
                        choices=[
                            ("design", "Design"),
                            ("inProgress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("onepdescription", models.CharField(max_length=200)),
                ("onepaddress", models.CharField(max_length=200, null=True)),
                ("oneplatitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("oneplongitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "oneplocation",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "coordinatorname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oneproject_projects",
                        to="mapagnt.projectcoordinatorinformation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "oneppmodel",
            },
        ),
        migrations.CreateModel(
            name="twopproject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("twopname", models.CharField(max_length=100)),
                (
                    "twoptype",
                    models.CharField(
                        choices=[
                            ("pipeline", "Pipe Line"),
                            ("highwayconstruction", "Highway Construction"),
                            ("roadrehabilitation", "Road Rehabilitation"),
                            ("drainagerehabilitation", "Drainage Rehabilitation"),
                            ("bridgesandtunnels", "Bridges and Tunnels"),
                        ],
                        max_length=50,
                    ),
                ),
                ("twopbudget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "twopstatus",
                    models.CharField(
                        choices=[
                            ("design", "Design"),
                            ("inProgress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("onepdescription", models.CharField(max_length=200)),
                ("twopaddress", models.CharField(max_length=200, null=True)),
                ("twopstartlat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("twopstartlon", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "twopstart_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("twopendlat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("twopendlon", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "twopend_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "coordinatorname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twoproject_projects",
                        to="mapagnt.projectcoordinatorinformation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "twopproject",
            },
        ),
        migrations.DeleteModel(
            name="PipelineProject",
        ),
        migrations.DeleteModel(
            name="projectsmapmodel",
        ),
        migrations.DeleteModel(
            name="RoadRehabilitationProject",
        ),
    ]
