# Generated by Django 5.0.2 on 2024-04-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapagnt", "0008_projectcoordinatorinformation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="projectcoordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coordinatorname", models.CharField(max_length=100)),
                ("coordinatordesignation", models.CharField(max_length=100)),
                ("coordinatoremail", models.EmailField(max_length=254)),
                ("coordinatorphnumber", models.CharField(max_length=15)),
                ("coordinatoraddress", models.CharField(max_length=200)),
                ("coordinatorzip_code", models.CharField(max_length=20)),
                ("coordinatorcity", models.CharField(max_length=100)),
                ("coordinatorstate", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="twopproject",
            old_name="onepdescription",
            new_name="twopdescription",
        ),
        migrations.AlterField(
            model_name="onepproject",
            name="coordinatorname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oneproject_projects",
                to="mapagnt.projectcoordinator",
            ),
        ),
        migrations.AlterField(
            model_name="twopproject",
            name="coordinatorname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="twoproject_projects",
                to="mapagnt.projectcoordinator",
            ),
        ),
        migrations.DeleteModel(
            name="projectcoordinatorinformation",
        ),
    ]
