# Generated by Django 5.0.2 on 2024-04-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapagnt", "0009_projectcoordinator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcoordinator",
            name="coordinatordesignation",
            field=models.CharField(
                choices=[
                    ("projectmanager", "Project Manager"),
                    ("seniorcivilengineer", "Sr. Civil Engineer"),
                    ("juniorcivilengineer", "Jr. Civil Engineer"),
                    ("siteengineer", "Site Engineer"),
                    ("labourcoordinator", "Labour Coordinator"),
                ],
                max_length=100,
            ),
        ),
    ]
