# Generated by Django 5.0.2 on 2024-04-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapagnt", "0010_alter_projectcoordinator_coordinatordesignation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onepproject",
            name="coordinatorname",
        ),
        migrations.RemoveField(
            model_name="twopproject",
            name="coordinatorname",
        ),
        migrations.AddField(
            model_name="onepproject",
            name="onecoordinatorname",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="twopproject",
            name="twocoordinatorname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
