# Generated by Django 5.0.2 on 2024-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapagnt", "0011_remove_onepproject_coordinatorname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onepproject",
            name="onepbudget",
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
        migrations.AlterField(
            model_name="twopproject",
            name="twopbudget",
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
    ]
