# Generated by Django 5.1.4 on 2026-04-02 19:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapagnt', '0012_alter_onepproject_onepbudget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('NH', 'National Highway'), ('SH', 'State Highway'), ('MDR', 'Major District Road'), ('ODR', 'Other District Road'), ('VR', 'Village Road')], max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='gray', help_text='Map display color, e.g. red, #FF5500', max_length=20)),
                ('weight', models.IntegerField(default=3, help_text='Map line weight in pixels')),
            ],
            options={
                'verbose_name_plural': 'Road Types',
            },
        ),
        migrations.AddField(
            model_name='twopproject',
            name='carriageway_width',
            field=models.FloatField(blank=True, help_text='Width in meters', null=True),
        ),
        migrations.AddField(
            model_name='twopproject',
            name='end_chainage',
            field=models.FloatField(blank=True, help_text='End chainage in meters', null=True),
        ),
        migrations.AddField(
            model_name='twopproject',
            name='lanes',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='twopproject',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='Full route geometry as LineString', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='twopproject',
            name='start_chainage',
            field=models.FloatField(default=0, help_text='Start chainage in meters'),
        ),
        migrations.CreateModel(
            name='ChainageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chainage', models.FloatField(help_text='Distance along route in meters')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic point at this chainage', srid=4326)),
                ('event_type', models.CharField(choices=[('milestone', 'Milestone'), ('intersection', 'Intersection'), ('tollbooth', 'Toll Booth'), ('restarea', 'Rest Area'), ('accident_zone', 'Accident Zone'), ('construction', 'Construction Zone'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainage_events', to='mapagnt.twopproject')),
            ],
            options={
                'verbose_name_plural': 'Chainage Events',
                'ordering': ['chainage'],
            },
        ),
        migrations.CreateModel(
            name='RoadAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('pole', 'Electric Pole'), ('sign', 'Sign Board'), ('drain', 'Drain'), ('bridge', 'Bridge'), ('culvert', 'Culvert'), ('traffic_signal', 'Traffic Signal'), ('streetlight', 'Street Light'), ('guardrail', 'Guard Rail')], max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('chainage', models.FloatField(help_text='Chainage along the road in meters')),
                ('condition', models.CharField(choices=[('good', 'Good'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('critical', 'Critical')], default='good', max_length=50)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Extra attributes as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_assets', to='mapagnt.twopproject')),
            ],
            options={
                'verbose_name_plural': 'Road Assets',
                'ordering': ['chainage'],
            },
        ),
        migrations.CreateModel(
            name='AssetInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('condition', models.CharField(choices=[('good', 'Good'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('critical', 'Critical')], max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapagnt.projectcoordinator')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='mapagnt.roadasset')),
            ],
            options={
                'verbose_name_plural': 'Asset Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AddField(
            model_name='twopproject',
            name='road_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='mapagnt.roadtype'),
        ),
    ]
